### PR TITLE
Add and config coverage badge plugin

### LINKED ISSUE #7: [Feature] Add test coverage logic/support with jest
The basics of jest are setup, but we should have test coverage support provided somehow so we can show it as a badge in the README.md

### PR DESCRIPTION
**Pull request by mihmilicio**
**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[X] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**
Installed the make-coverage-badge plugin, to generate the coverage badge in the coverage folder (customizable) 
**Which issue (if any) does this pull request address?**
Fix #7 
**Is there anything you'd like reviewers to focus on?**

### CODE REVIEW

**Comment by bradtaniguchi** [comment]
So I just ran `npm run test:coverage` on my side, but I'm not sure how to use the generated `svg` to get the coverage. 

Currently we are using `github-actions` for our CI/CD, will it be needed to save/use the saved svg? 

We don't have to add full support in this PR, we can create other issues and we can create the PRs later, but I would like to know how we plan to use these changes, or at least were we can go to learn about using it more :)

**Comment by mihmilicio** [comment]
I was searching a bit, and I think we shouldn't gitignore the badge itself. So in the readme, we could just put a relative path to the image. 

As for gh actions, I'm not familiar with it, but as I searched I think we should do something like this: 
```
name: Push commit
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update coverage
        run: npm run test:coverage
      - name: Commit badge
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated coverage badge"
          git push
```

By the morning I can fix the gitignore thing and give you the image link to put in the readme

**Comment by mihmilicio** [comment]
Now in the readme you can probably insert the badge using: 
```
![Test coverage badge](/coverage/badge.svg?raw=true)
```

**Review by bradtaniguchi — APPROVED** [review]
There might be a cleaner way to get the coverage badge instead of saving it to the source, but I think we can figure that it out in another PR :+1:

**Pull request merged**
