### PR TITLE
Adding Badges to README.md

### PR DESCRIPTION
**Pull request by LandonLloyd**
**What is the purpose of this pull request? (put an "X" next to item)**

- [X] Documentation update
- [ ] Bug fix
- [X] New feature
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**
I added some badges to the project README.md file.
**Which issue (if any) does this pull request address?**
[CHORE] Add readme badges
**Is there anything you'd like reviewers to focus on?**
I couldn't find a badge for ``tested`` but I also added a fun one called hitcounter to track the amount of times someone opens this repo!

### CODE REVIEW

**Review by bradtaniguchi — COMMENTED** [review]
Is it possible to change the `hits` one to the same "theme" as the others? Or even replaced/dropped. I'm not sure why the TypeScript one seems larger either, we can keep it if need be, but if there is a "smaller" version that is the same size as the others that would be better :)

This is what I see:
image

**Comment by LandonLloyd** [comment]
Ok. I am not sure on the hit counter one but I will try and find a smaller typescript one, I will also add the MIT one to the License header if you want.

**Comment by bradtaniguchi** [comment]
No need for badges in other files I think, the "flashiness" can stay in just the README ;D

**Comment by LandonLloyd** [comment]
But like how you have different sections of the readme you have one for license and then with a link for the MIT do you want a badge down there too?

**Comment by LandonLloyd** [comment]
Alright I changed some things around. Feel free to edit anything!

**Review by bradtaniguchi — APPROVED** [review]
LGTM :+1:

We can always update/change the badges later, but this should be good for now

Thanks for your contributions!

**Pull request merged**
